// AUTO-GENERATED by tools/build_progress.py — do not edit by hand.
const PROGRESS = {
  "generated": "2026-08-30",
  "planStart": "2026-08-31",
  "planEnd": "2026-12-06",
  "tracks": [
    {
      "key": "week-0",
      "total": 91,
      "done": 0
    },
    {
      "key": "week-1",
      "total": 64,
      "done": 0
    },
    {
      "key": "audit",
      "total": 20,
      "done": 4
    },
    {
      "key": "master",
      "total": 155,
      "done": 0
    },
    {
      "key": "mha",
      "total": 12,
      "done": 0
    }
  ],
  "weeks": [
    {
      "label": "W0-A",
      "start": "2026-08-31",
      "end": "2026-09-06"
    },
    {
      "label": "W0-B",
      "start": "2026-09-07",
      "end": "2026-09-13"
    },
    {
      "label": "W1",
      "start": "2026-09-14",
      "end": "2026-09-20"
    },
    {
      "label": "W2",
      "start": "2026-09-21",
      "end": "2026-09-27"
    },
    {
      "label": "W3",
      "start": "2026-09-28",
      "end": "2026-10-04"
    },
    {
      "label": "W4",
      "start": "2026-10-05",
      "end": "2026-10-11"
    },
    {
      "label": "W5",
      "start": "2026-10-12",
      "end": "2026-10-18"
    },
    {
      "label": "W6",
      "start": "2026-10-19",
      "end": "2026-10-25"
    },
    {
      "label": "W7",
      "start": "2026-10-26",
      "end": "2026-11-01"
    },
    {
      "label": "W8",
      "start": "2026-11-02",
      "end": "2026-11-08"
    },
    {
      "label": "W9",
      "start": "2026-11-09",
      "end": "2026-11-15"
    },
    {
      "label": "W10",
      "start": "2026-11-16",
      "end": "2026-11-22"
    },
    {
      "label": "W11",
      "start": "2026-11-23",
      "end": "2026-11-29"
    },
    {
      "label": "W12",
      "start": "2026-11-30",
      "end": "2026-12-06"
    }
  ],
  "days": {
    "week0": [
      {
        "day": 1,
        "date": "2026-08-31",
        "total": 7,
        "done": 0
      },
      {
        "day": 2,
        "date": "2026-09-01",
        "total": 6,
        "done": 0
      },
      {
        "day": 3,
        "date": "2026-09-02",
        "total": 9,
        "done": 0
      },
      {
        "day": 4,
        "date": "2026-09-03",
        "total": 6,
        "done": 0
      },
      {
        "day": 5,
        "date": "2026-09-04",
        "total": 6,
        "done": 0
      },
      {
        "day": 6,
        "date": "2026-09-05",
        "total": 11,
        "done": 0
      },
      {
        "day": 7,
        "date": "2026-09-06",
        "total": 0,
        "done": 0
      },
      {
        "day": 8,
        "date": "2026-09-07",
        "total": 5,
        "done": 0
      },
      {
        "day": 9,
        "date": "2026-09-08",
        "total": 3,
        "done": 0
      },
      {
        "day": 10,
        "date": "2026-09-09",
        "total": 7,
        "done": 0
      },
      {
        "day": 11,
        "date": "2026-09-10",
        "total": 6,
        "done": 0
      },
      {
        "day": 12,
        "date": "2026-09-11",
        "total": 9,
        "done": 0
      },
      {
        "day": 13,
        "date": "2026-09-12",
        "total": 14,
        "done": 0
      },
      {
        "day": 14,
        "date": "2026-09-13",
        "total": 2,
        "done": 0
      }
    ],
    "week1": [
      {
        "day": 1,
        "date": "2026-08-31",
        "total": 9,
        "done": 0
      },
      {
        "day": 2,
        "date": "2026-09-01",
        "total": 14,
        "done": 0
      },
      {
        "day": 3,
        "date": "2026-09-02",
        "total": 10,
        "done": 0
      },
      {
        "day": 4,
        "date": "2026-09-03",
        "total": 11,
        "done": 0
      },
      {
        "day": 5,
        "date": "2026-09-04",
        "total": 8,
        "done": 0
      },
      {
        "day": 6,
        "date": "2026-09-05",
        "total": 9,
        "done": 0
      },
      {
        "day": 7,
        "date": "2026-09-06",
        "total": 3,
        "done": 0
      }
    ]
  },
  "tiers": [
    {
      "tier": 0,
      "name": "Tier 0 · 阻塞型（缺了后面全塌）",
      "green": 0,
      "yellow": 2,
      "red": 10
    },
    {
      "tier": 1,
      "name": "Tier 1 · LLM 专属背景",
      "green": 0,
      "yellow": 7,
      "red": 3
    },
    {
      "tier": 2,
      "name": "Tier 2 · 视觉与多模态（你最可能空的一块）",
      "green": 0,
      "yellow": 3,
      "red": 7
    },
    {
      "tier": 3,
      "name": "Tier 3 · 经典 ML 与统计",
      "green": 0,
      "yellow": 8,
      "red": 0
    }
  ]
};
