#!/usr/bin/env python3
"""从 blog/posts 下的计划 markdown 解析进度，生成 progress-data.js。

只提取聚合数字（勾选数 / 自查档位 / 日期），不导出任何任务文本。
用法：python3 tools/build_progress.py
"""
import json, os, re, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
POSTS = os.path.join(ROOT, "blog", "posts")

BOX = re.compile(r"^\s*[-*]\s*\[( |x|X)\]")

def count_boxes(lines):
    total = done = 0
    for ln in lines:
        m = BOX.match(ln)
        if m:
            total += 1
            done += 1 if m.group(1).lower() == "x" else 0
    return total, done

def read(path):
    with open(os.path.join(POSTS, path), encoding="utf-8") as f:
        return f.read().split("\n")

# ── Week 0 / Week 1 的逐日进度 ───────────────────────────────
DAY = re.compile(r"^##\s*Day\s*(\d+)\s*·\s*\S+\s*(\d+/\d+)")

def parse_days(path, year=2026):
    lines = read(path)
    days, cur = [], None
    for ln in lines:
        m = DAY.match(ln)
        if m:
            mm, dd = m.group(2).split("/")
            cur = {"day": int(m.group(1)),
                   "date": f"{year}-{int(mm):02d}-{int(dd):02d}",
                   "total": 0, "done": 0}
            days.append(cur)
            continue
        b = BOX.match(ln)
        if b and cur is not None:
            cur["total"] += 1
            cur["done"] += 1 if b.group(1).lower() == "x" else 0
    return days

# ── 自查表档位统计 ──────────────────────────────────────────
TIER_HDR = re.compile(r"^###\s*Tier\s*(\d)")

def parse_tiers():
    lines = read("plan/foundations-audit.md")
    tiers, cur = [], None
    for ln in lines:
        m = TIER_HDR.match(ln)
        if m:
            name = ln.lstrip("# ").strip()
            cur = {"tier": int(m.group(1)), "name": name,
                   "green": 0, "yellow": 0, "red": 0}
            tiers.append(cur)
            continue
        if cur is None or not ln.startswith("|"):
            continue
        cells = [c.strip() for c in ln.strip("|").split("|")]
        if len(cells) < 3 or not cells[0].isdigit():
            continue
        mark = "".join(cells)
        if "✅" in mark: cur["green"] += 1
        elif "🟡" in mark: cur["yellow"] += 1
        elif "❌" in mark: cur["red"] += 1
    return [t for t in tiers if t["green"] + t["yellow"] + t["red"]]

# ── 14 周时间线 ─────────────────────────────────────────────
TL = re.compile(r"^\|\s*\**\s*(Week\s*0-[AB]|W\d+)\s*\**\s*\|\s*([\d/]+)\s*[–-]\s*([\d/]+)\s*\|")

def parse_timeline(year=2026):
    weeks = []
    for ln in read("mllm-interview-prep-plan.md"):
        m = TL.match(ln)
        if not m:
            continue
        def iso(s):
            mm, dd = s.split("/")
            return f"{year}-{int(mm):02d}-{int(dd):02d}"
        weeks.append({"label": m.group(1).replace("Week ", "W"),
                      "start": iso(m.group(2)), "end": iso(m.group(3))})
    return weeks

# ── 组装 ────────────────────────────────────────────────────
files = {
    "week-0":  "plan/week-00-foundations.md",
    "week-1":  "plan/week-01-daily.md",
    "audit":   "plan/foundations-audit.md",
    "master":  "mllm-interview-prep-plan.md",
    "mha":     "kownledgebase/mha-recovery.md",
}
tracks = []
for key, path in files.items():
    total, done = count_boxes(read(path))
    tracks.append({"key": key, "total": total, "done": done})

data = {
    "generated": datetime.date.today().isoformat(),
    "planStart": "2026-08-31",
    "planEnd": "2026-12-06",
    "tracks": tracks,
    "weeks": parse_timeline(),
    "days": {"week0": parse_days(files["week-0"]),
             "week1": parse_days(files["week-1"])},
    "tiers": parse_tiers(),
}

out = os.path.join(ROOT, "progress-data.js")
with open(out, "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by tools/build_progress.py — do not edit by hand.\n")
    f.write("const PROGRESS = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n")
print("wrote", out)
